redis:
    password: ENC[AES256_GCM,data:T1GjHhp2BQpdf3SzrfKBBEJkgEc=,iv:tVXTJLJpJmhP4mNIq5oRQFVGDp0iAUUyVGe14RD861U=,tag:ewkC6AbEfSvORT2JKsHvjg==,type:str]
env: ENC[AES256_GCM,data:IUB26cUcAcKY8cnqYpaoQC6bW1j5caYBs/LYTI2XSytqxvgTkOJaEY0EOU9Eqq6WxQY2FpzNVGDphsiXlubTmgjUI/yQ7tP7SnDK+KOXo+5NRxLOhcdc5eFRMQbzlGbcfMNxP4P2FT7ilksMUvwUnKh5ob7Emas08wMx8sdUHCDRJDC7hougB05TNbkW8hunFoG+t4knZ1cthC79YYzf2L0eGAUYTu1jMZBxaG/w5brUSwMhYhnhTHOC9rY1FTynjXdm3yY3az6xXG/6TBRd24GoZQcugs5cyc/pbNyKhoxOukCw3cZiWpdqcqVca2XAuARYHx5gyhkZhVv/dyfEHZdIIJFvxkiGabNicGbMsFVtosH6zl91rezLGVUSdOVSjWjfQMOQxbF7JE5TvDiB5Kyyjf7njSuOhNfng9gglLPMI00GUaE1bOE8pHrE3m6nX2C7ESrU0TQrVhQO2apL5VF2o9g1Tq/aIQg2/MQJFMd0GA+2oCrQKPGwRUu5J1tlpHtaDd+9NCM5qny+NPodP/NgXJU/UCC/RdbA2Q3enykmu3+9oHWLH13wMqVU09hR73l4dkOCtPaxRxOHIZADRwefniw1Ik8ZmYeGNPOVwnwJc48HcCjf5P/Oe2I+RVodXDylzvjOu3lhmFgKnSnNMCkOm2YCljesNfjOvguY6gmYtJyF4MhaKTtmV5ohKapQRiAdlNSKOyJG6pSuKDCtO2WGuM1E03KWrU70jejCX4MgxkcUSw6MJgGpWyu52JQPcm0LiYJezDDEpX3c5xU3fQaNKDUKZbBOAWEVHdyazwSc3klvWamog9UJZvECdzinxHJbXNoVrOQ9ZeoyyAEBhESjb4C06J06cj5daZ2uW4IYGyGA7pldKPENVbehjtrwCHrXarEJbKwh/6mOR0P4YrlzbJJkAXinK5VBLFrzxNuDIynj2CxB9I1MiGnGPlzD8e1YSscnFgccYdLka64n00pMwzXcodXPWCYOfbEugXu2HqgurlQmT4CA+HG1KeGvH4l0YCTSjg5FHb5+YjfgXMISOg+V,iv:UGocrdQ439oWIlFyMB9VXh0yoR/K5triozDkCTFQGBI=,tag:ALbXCRgHiF0XuKBK+CxW6A==,type:str]
sops:
    age:
        - recipient: age1x9kwej7qejzkr5n3gz6wxecq9a5kq2rcf9lpg4t36638mtwlgylsahwhgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcmFKa3FUSWNGNEozRGhh
            OFFmZ2Z3WEtSMU9BWW00aW5OYW92NHdRbkMwClc2aHBFTENkVFZLRjZxTm5TS3ZG
            ekFONS9sSnpuOXhmSDNOL1hDLzZLQVEKLS0tIFJzZDN1eXpYL3NPdm5remFsMVpk
            Y1lmdjU3dDlsbFhFMk4rOXZXOFpMbm8KMyUIKhvkyIs+11QN3j1QrLUSORUCSt8X
            yY4ooGPScmT/vZ/+4WramJUEITZlpDtiauY7snjAJcKSKxI8wxDpWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fhqqzfkn6wp2dklplgmd6gsfg67vhwqlcx8vxug50lsrs0fcjv8sx8xsg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWlVUVjVTVE5ZMDF4TEZL
            NFF5YXZ3YjA4YmdLQnRuT2JIRnRkNGVtTHh3CkpFTDY2dDUzYWhrRU1nNEJ1bGM0
            MTZJTnBBaDR6QlFqMmNaKzQzTEMyU2cKLS0tIFJmM2FyWlV4YldsZjNFMHVsbk1V
            cjVvcTlhNW9NSEp1MG1WRWpoOS9HdlUKgN6dJFIMNCc5LvXf9Rt+SMtCUej9YA5P
            VVfx3OY4Bwmt6KhS68KSszhTaqGAQZTEpm0F7EcjpbM2n2/jd2dEvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19c408yytfpxd0dy9lj85jhx9tgyxsl9gdy544fqs8t4g9xka6cysp5xw3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvazV5YWxuQm4yQWgrc0Ri
            eUJxakpRRS9FV3RubkpRYnREbC9wTzU1OG5nCncrbmNrWEFqa0o0K2FnUkxJZFlR
            Ni9CWGsrdUZPT3I0dlVXa3Nka2h0WTQKLS0tIEFOeTNyY0JrNStkb05VdGh6bkln
            ZmJTWHM5K1RWT2hpUTRKaEF6cFJGeVUKT3XBQgRGOQfLJ20OxqaTRL01gOl8iBHZ
            //353JJzvULu+I8DHSo49u28SqDEfTkfuirIcaSz2AwpKiCtKW3TuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ncw02zdtee3w8m3g6a97u97d0xlmmt0v4mjgdvqdxw0wge46cksml6fvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZEpTd3dGUEtkOSt6VzQz
            WWxZYVJLYVdPN0c2Mk9tczJkeDl1ZXdZR1U0ClZNUkdnV3VjUUxRS2xmUkU2VzZW
            Y1BHOG51dTl5QjFCK2tjeVRWRmZDZHMKLS0tIDdsUXl1MjlaVFIrRGdISmYzWmlP
            dnlpTkJMelJQbWJINUQzem1JYXgvTmcKX1DZwxj0TbRaFuLrFxj8ct9L63mSsQPw
            TgFsVCJZF6oixhwV/NtK19wbJGMD4Tm+iCOSQmeLo9b3mDlftlQBcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T11:19:11Z"
    mac: ENC[AES256_GCM,data:SLD+LVxInn9H6WAtsFoj+2Pd1H1QaeIshP5aYgD0XaHiyjiNBEt9ilW7mGNjjxuCrk8gxjnsde4zQYdWztS9QWulcAWArqpl073+4asq+vgdQyRvKPKWb733V7xVzir/wgQqyapzeh6cbBAyl617VxN+YK3qgV9iWT30ccNrxY8=,iv:ZCkVyQym/6TIm8QXk6yA77Yl7sGTqyOEQIToumoQk2g=,tag:WOUMUidwcP6vELvnbvbljA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
