db:
    postgres:
        masterPassword: ENC[AES256_GCM,data:GwH4uIzh29Y0nSHsd6Unh6ai0iE=,iv:pefZbgEUXChjEp5fYLeEtScTE01fSHj0qJ5MTQj4V+E=,tag:X6oMmPVnmhKovYb4XYi42Q==,type:str]
        databases:
            sonarqube:
                db:
                    name: ENC[AES256_GCM,data:jcX/P/y+W3vw3gg/aR7o,iv:3KKcMULCdbQ2fZhEG/bOFa3GTN0Rxefy+76dnGiGjiE=,tag:gNHlEURhvQax1VXSLZD1bg==,type:str]
                    schema: ENC[AES256_GCM,data:RlAVdA==,iv:0VMxsXtXH4Ztec8IL3L2oPr2Bv13dkSznQ4r3I4m1zk=,tag:p+dIVJTkEn0AZ30RbuTcMg==,type:str]
                users:
                    admin:
                        username: ENC[AES256_GCM,data:3LxICgH5Aw==,iv:BB6DyCkqn0RyfFAOFZsstXXnh6a+GKP6Kr+nAZMgfmc=,tag:nD0po7nO20Mms/NNHfab4Q==,type:str]
                        password: ENC[AES256_GCM,data:ZoAKzKGBIGaQwrzRRhh8EvH1u/w=,iv:8y2stQMD6VzjrzsQYABsac75ko3fvAOYrp4fmfDOKNo=,tag:TGFucrNfRQIZHerxS5iTfQ==,type:str]
                    reader:
                        username: ENC[AES256_GCM,data:cCNyxgfTz7g=,iv:XX3SbCLtfRVHTUOt+WEFgfcXsMKYe/n/wfTPdFRBBkU=,tag:Ev8itvSTBNRrf8Ixmi5igg==,type:str]
                        password: ENC[AES256_GCM,data:NtMXxQoulUlUbtqKnOpG+CLj9Do=,iv:cmmHC+RSf7r4GsWvn4caTf7g+pl7perOviHyE+919Js=,tag:00ikzpC0EAaOjvEsZM0LUw==,type:str]
                    writer:
                        username: ENC[AES256_GCM,data:p/Jo38WvctM=,iv:5l1+KACItkmv7ST30s7PPNCI+tpMPpNY1njhd9hCOHE=,tag:MsGLq1e3J1O5Nn+EFVAfnw==,type:str]
                        password: ENC[AES256_GCM,data:qP9CJqFsa9drKI8otzx5KGcV8fU=,iv:zjP27KfKt80ILseXqLQYE7CMz5aBzyavVQaZs8ZOQso=,tag:UlyMNc9wXgyx4MFUwX2MGQ==,type:str]
sops:
    age:
        - recipient: age1fhqqzfkn6wp2dklplgmd6gsfg67vhwqlcx8vxug50lsrs0fcjv8sx8xsg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcUVRSmUyZ3VsSjFGTFBK
            c3Y4MVVnV2pVdmFZcURGZ1dzS2ZzY2NJRnk4ClJDT1A3MUY1Y3ptclhHSGFLOURR
            aW83OHhBTGFHd0tNc2E1ckFmTE9PN3cKLS0tIDQ0ZkMxWVh6VmFIazdVSG9nOW5U
            R1dOSXBLbXlGVjh0VCt1QXZicTBZSXMKqyzPI/Arvc+YErwM3SldgF5VYpJBkrTv
            XX12Sfw7bsnduDZAA4ISyyIZAjjwG2HPdF4lWqcW9fZxA8dEZVgs8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9kwej7qejzkr5n3gz6wxecq9a5kq2rcf9lpg4t36638mtwlgylsahwhgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdk9YckZseXd4TUEreW9P
            WlRpR3ArZVBPbktRcFdpS09uK0pzWmdYVGdvCk0wWkdlMUZkWWlXWkd3c0RHdHk3
            UDc3MU9WNWZSRXhPbWQrTU1DZ09RNG8KLS0tIFpnY083NEhCdGVXR0tWWkhoamVs
            aGlUSEoySzh3ZEdQUnlFbmtWdFhKVlUKF9AkCLBNq53hwlnmyuyFdz6b/n/WJ2Na
            aSaojo4uiLwgBgL6F3b5U3tPsfqRwT2g7r9XQYV8Q0mG8WSmouOadA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T05:51:51Z"
    mac: ENC[AES256_GCM,data:Z5Bsnbjj6MYvp064T7SqZxwnssWqePZypxVHokH8yub0EuChby2b7YHvkMsVLYQN6WSu7oT1dlDXrt+jZv5pVds/az/TkPr5quT2Q11QlluqbDhWjs1QHSdTs3+RYn1SxqKrpopnBKNpPd3vRMzXNDSApxReTvXZBAAXCo+Ip8A=,iv:rHzxp0PCkPoYbuJXTRijKeartg4kpSSZuTS2I4GMC00=,tag:Aw34CsRxX2CS6MX0e2qwBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
