version: 3
tasks:
  ssh2age:
    desc: "Generate Age private key from SSH private key"
    vars:
      SSH_FILE: "{{ index .CLI_ARGS_LIST 0 }}"
      OUTPUT_FILE: "{{ index .CLI_ARGS_LIST 1 }}"
    cmds:
      - read -s SSH_TO_AGE_PASSPHRASE; export SSH_TO_AGE_PASSPHRASE
      - ssh-to-age --private-key -i {{ .SSH_FILE }} -o {{ .OUTPUT_FILE }}
      - unset SSH_TO_AGE_PASSPHRASE;
  ssh2age:pub:
    desc: "Generate Age public key from SSH public key"
    vars:
      SSH_FILE: "{{ index .CLI_ARGS_LIST 0 }}"
      OUTPUT_FILE: "{{ index .CLI_ARGS_LIST 1 }}"
    cmds:
      - read -s SSH_TO_AGE_PASSPHRASE; export SSH_TO_AGE_PASSPHRASE
      - ssh-to-age -i {{ .SSH_FILE }} -o {{ .OUTPUT_FILE }}
      - unset SSH_TO_AGE_PASSPHRASE;
  edit:host-user:
    desc: "Edit user host secrets"
    cmds:
      - sops ./secrets/$(hostname)/$(whoami)/default.yaml
  edit:host:
    desc: "Edit host secrets"
    cmds:
      - sops ./secrets/$(hostname)/default.yaml
